"""
Convert CSS file into a C header file for embedding in firmware.

Usage:
    python css2header.py -f ./html/styles.css -o ./generated/styles.css.h
"""

import argparse
import os

C_HEADER_TEMPLATE = """// ---------------------------------------------------------- //
// This file is autogenerated by css2header.py; do not edit!  //
// ---------------------------------------------------------- //

#ifndef {capitalized_filename}_H_
#define {capitalized_filename}_H_

const char css_{lowercase_filename}[] = "{css_string}";

#endif  //  {capitalized_filename}_H_
"""


def main(input_filepath, output_filepath):
    with open(input_filepath, 'r', encoding='utf-8') as fp:
        input_file = fp.read()

    # Prepend HTTP header for CSS
    css_with_header = "HTTP/1.1 200 OK\r\nContent-Type: text/css\r\nCache-Control: max-age=86400\r\n\r\n" + input_file

    # Escape characters for C string
    escaped_css = css_with_header.replace("\\", "\\\\")
    escaped_css = escaped_css.replace('"', '\\"')
    escaped_css = escaped_css.replace("'", "\\'")
    escaped_css = escaped_css.replace("\n", "\\n")
    escaped_css = escaped_css.replace("\r", "\\r")

    filename = os.path.basename(input_filepath)
    filename = filename.replace('.', '_').replace('-', '_')

    c_header_string = C_HEADER_TEMPLATE.format(
        capitalized_filename=filename.upper(),
        lowercase_filename=filename.lower(),
        css_string=escaped_css,
    )

    with open(output_filepath, 'w', encoding='utf-8') as fp:
        fp.write(c_header_string)

    print(f"Generated {output_filepath} ({len(escaped_css)} bytes)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--input_filepath', required=True)
    parser.add_argument('-o', '--output_filepath', required=True)
    args = parser.parse_args()
    main(args.input_filepath, args.output_filepath)
